puppetlabs/puppetlabs-dsc_lite

- README.md
- lib/puppet/provider/base_dsc_lite/invoke_generic_dsc_resource.ps1.erb
- lib/puppet/type/dsc.rb
- lib/puppet_x/puppetlabs/dsc_lite/powershell_hash_formatter.rb
- spec/integration/puppet_x/puppetlabs/powershell_hash_formatter_spec.rb
This commit adds support for EmbeddedInstances (complex types and CIM Instances) when using `Invoke-DscResource` with the generic dsc type.
This commit also updates the `Usage` section of the README to reflect the usage of the dsc type. It does not attempt to update the entire README to reflect the changes from the dsc module, as that is out of scope for this PR.
> (MODULES-6323) EmbeddedInstance support

- README_Tradeoffs.md
Prior to this commit there is no information captured
in the repository for _why_ a user might (and might
not) want to switch from `DSC` to `DSC_Lite`. This
commit adds that information for potential users.
> (MODULES-5847) Clarify tradeoffs

- README_Tradeoffs.md
Some of the wording the tradeoffs is unclear or
grammatically incorrect. This maintenance commit
fixes those problems.
CC @clairecadman
> (MAINT) Clarify tradeoffs wording

- tests/acceptance/tests/basic_dsc_resources/dsc_before_puppet_type.rb
- tests/acceptance/tests/basic_dsc_resources/dsc_require_puppet_type.rb
- tests/acceptance/tests/basic_functionality/alternate_path_separator.rb
- tests/acceptance/tests/basic_functionality/puppet_apply_debug_dsc_manifest.rb
- tests/acceptance/tests/basic_functionality/puppet_apply_dsc_manifest.rb
- tests/acceptance/tests/basic_functionality/puppet_apply_noop_dsc_manifest.rb
- tests/integration/tests/basic_functionality/negative/dsc_on_linux.rb
- tests/integration/tests/basic_functionality/puppet_agent_debug_dsc_manifest.rb
- tests/integration/tests/basic_functionality/puppet_agent_dsc_manifest.rb
- tests/integration/tests/basic_functionality/puppet_agent_noop_dsc_manifest.rb
- tests/integration/tests/dsc_type/custom_resource_from_system_PSModulePath.rb
- tests/integration/tests/dsc_type/custom_resource_path.rb
- tests/integration/tests/dsc_type/multiple_dsc_resources_in_PSModulePath.rb
- tests/integration/tests/dsc_type/psdesiredstateconfiguration.rb
- tests/integration/tests/ensure_behavior/ensure_absent.rb
- tests/integration/tests/ensure_behavior/ensure_absent_and_dsc_ensure_present.rb
- tests/integration/tests/ensure_behavior/ensure_and_dsc_ensure_absent.rb
- tests/integration/tests/ensure_behavior/ensure_and_dsc_ensure_present.rb
- tests/integration/tests/ensure_behavior/ensure_present.rb
- tests/integration/tests/ensure_behavior/ensure_present_and_dsc_ensure_absent.rb
- tests/manifests/basic_functionality/test_file_path.pp.erb
Reverts puppetlabs/puppetlabs-dsc_lite#26
The inline templates used ERB `<%= %>` syntax instead of Ruby `#{}` syntax
> Revert "(maint) Acceptance test minor cleanup"

- tests/acceptance/tests/basic_dsc_resources/multi_failing_dsc_resources.rb
- tests/acceptance/tests/basic_dsc_resources/some_failing_dsc_resources.rb
- tests/acceptance/tests/basic_functionality/alternate_path_separator.rb
- tests/acceptance/tests/basic_functionality/negative/dsc_on_linux.rb
- tests/acceptance/tests/basic_functionality/puppet_apply_debug_dsc_manifest.rb
- tests/acceptance/tests/basic_functionality/puppet_apply_dsc_manifest.rb
- tests/acceptance/tests/basic_functionality/puppet_apply_noop_dsc_manifest.rb
- tests/acceptance/tests/dsc_type/custom_resource_from_system_PSModulePath.rb
- tests/acceptance/tests/dsc_type/custom_resource_path.rb
- tests/acceptance/tests/dsc_type/multiple_dsc_resources_in_PSModulePath.rb
- tests/acceptance/tests/ensure_behavior/ensure_absent.rb
- tests/acceptance/tests/ensure_behavior/ensure_and_dsc_ensure_present.rb
- tests/acceptance/tests/ensure_behavior/ensure_present.rb
- tests/acceptance/tests/ensure_behavior/ensure_present_and_dsc_ensure_absent.rb
- tests/lib/dsc_utils.rb
Note that there are a few tests that did not yet work with the new `dsc` resource:
* ensure_absent_and_dsc_ensure_present.rb
* ensure_and_dsc_ensure_absent.rb
The current resource does not have the same code as the type wrapper for hooking up with the reboot resource.
I suggest for both of these additional tickets be filed to address as it's new functionality not yet implemented in the generic resource.
> (MODULES-6552) Use generic dsc type in Beaker manifests

- README.md
- README_Tradeoffs.md
- lib/puppet/provider/base_dsc_lite/invoke_generic_dsc_resource.ps1.erb
- lib/puppet/type/dsc.rb
- spec/unit/puppet/type/dsc_spec.rb
- tests/acceptance/tests/basic_dsc_resources/multi_failing_dsc_resources.rb
- tests/acceptance/tests/basic_dsc_resources/some_failing_dsc_resources.rb
- tests/acceptance/tests/basic_functionality/alternate_path_separator.rb
- tests/acceptance/tests/basic_functionality/negative/dsc_on_linux.rb
- tests/acceptance/tests/basic_functionality/puppet_apply_debug_dsc_manifest.rb
- tests/acceptance/tests/basic_functionality/puppet_apply_dsc_manifest.rb
- tests/acceptance/tests/basic_functionality/puppet_apply_noop_dsc_manifest.rb
- tests/acceptance/tests/dsc_type/custom_resource_from_system_PSModulePath.rb
- tests/acceptance/tests/dsc_type/custom_resource_path.rb
- tests/acceptance/tests/dsc_type/multiple_dsc_resources_in_PSModulePath.rb
- tests/acceptance/tests/dsc_type/psdesiredstateconfiguration.rb
- tests/acceptance/tests/ensure_behavior/ensure_absent.rb
- tests/acceptance/tests/ensure_behavior/ensure_and_dsc_ensure_present.rb
- tests/acceptance/tests/ensure_behavior/ensure_present.rb
- tests/acceptance/tests/ensure_behavior/ensure_present_and_dsc_ensure_absent.rb
This commit changes `dsc_resource_module_name` to `dsc_resource_module`, and updates it to accept both a string or a hash with two specific key/value pairs
> (MODULES-5845) Add DSC Resource ModuleSpecification support

- metadata.json
I had been using the 2.0.0 version of the reboot module and noticed that when using PMT to install dsc_lite it blows up because the module i have locally doesn't fall within an acceptable version for dsc_lite as specified in the metadata.json.  Just bumping the dependency and would like someone to review to make sure they don't forsee any issues with this.
> (maint) Allow reboot 2.0+ module dependency

- CHANGELOG.md
Update the changelog to reflect the change in the metadata file so that
the new version of the puppetlabs-reboot doesn't cause problems.
> (MAINT) Update changelog for reboot dependancy

- lib/puppet_x/puppetlabs/dsc_lite/templates/init_ps.ps1
The newest image for Windows 2008r2 is exhibiting different behavior
for loading .NET assemblies than we have seen in the past. The
System.Core assembly is not loaded into the PowerShell host process by
default any longer. This causes the init.ps1 script in the module to
to fail to start a Pipe Server to receive PowerShell scripts to be
executed. This change always attempts to load the System.Core
assembly prior to creating the pipe server object. Explicity loading the
assembly fixes the issue and the newest image becomes usable again.
> (MODULES-6930) Fix Pipes Server On windows2008r2

- README.md
Some DSC Resources parameters are `[PSCredential]` typed and require
passwords, but do not require user names to pair with the password. In
order to correctly specify a `PSCredential` with just a password, specify
a null string as the user name.
> (MODULES-6992) Document null username PSCredential

- README.md
This commit updates the README with documentation on how to install
DSC Resources on target nodes that can be used by the `dsc_lite` module.
> (MODULES-7105) Document DSC Resource Distribution

- .sync.yml
- appveyor.yml
Manually remove Puppet 4.2.3 testing from modulesync and appveyor as it
is no longer necessary.
> (maint) Remove appveyor 4.2.3 Puppet testing

- README.md
- lib/puppet/provider/base_dsc_lite/powershell.rb
- lib/puppet_x/puppetlabs/dsc_lite/dsc_type_helpers.rb
- lib/puppet_x/puppetlabs/dsc_lite/powershell_hash_formatter.rb
- spec/integration/puppet_x/puppetlabs/powershell_hash_formatter_spec.rb
- spec/unit/puppet_x/puppetlabs/dsc_type_helpers_spec.rb
This is a port of the code in [puppetlabs-dsc PR#324](https://github.com/puppetlabs/puppetlabs-dsc/pull/324) to add Sensitive types to the dsc_lite module.
> (MODULES-7141) Support Sensitive data type

- lib/puppet/provider/base_dsc_lite/powershell.rb
- tests/acceptance/tests/unicode/puppet_apply_utf8_file_name.rb
This PR adds UTF-8 support for fields inside of custom dsc templates.
It does not support the template custom name itself being in UTF-8, but parameters passed to fields in the template can now be UTF-8.
Also added an integration test for this functionality.
> (MODULES-7143) add UTF-8 encoding to ERB templates.

- CHANGELOG.md
- README.md
- README_Tradeoffs.md
- lib/puppet/provider/base_dsc_lite/invoke_generic_dsc_resource.ps1.erb
- lib/puppet/provider/base_dsc_lite/powershell.rb
- lib/puppet/type/dsc.rb
- spec/unit/puppet/type/dsc_spec.rb
- tests/acceptance/tests/basic_dsc_resources/multi_failing_dsc_resources.rb
- tests/acceptance/tests/basic_dsc_resources/some_failing_dsc_resources.rb
- tests/acceptance/tests/basic_functionality/negative/dsc_on_linux.rb
- tests/acceptance/tests/basic_functionality/puppet_apply_dsc_manifest.rb
- tests/acceptance/tests/basic_functionality/puppet_apply_noop_dsc_manifest.rb
- tests/acceptance/tests/dsc_type/custom_resource_from_system_PSModulePath.rb
- tests/acceptance/tests/dsc_type/custom_resource_path.rb
- tests/acceptance/tests/dsc_type/multiple_dsc_resources_in_PSModulePath.rb
- tests/acceptance/tests/dsc_type/psdesiredstateconfiguration.rb
- tests/acceptance/tests/unicode/puppet_apply_utf8_file_name.rb
Prior to this commit the dsc resource used the following long,
slightly repetitive names for the parameters:
- `dsc_resource_name`
- `dsc_resource_module`
- `dsc_resource_properties`
This commit replaces those names with the following:
- `resource_name`
- `module`
- `properties`
> (MODULES-7253) Replace verbose parameter names

- spec/acceptance/basic_dsc_resources/failing_dsc_resources_spec.rb
- spec/acceptance/basic_functionality/negative/dsc_on_linux_spec.rb
- spec/acceptance/basic_functionality/puppet_apply_dsc_manifest_spec.rb
- spec/acceptance/dsc_type/custom_resource_from_system_PSModulePath_spec.rb
- spec/acceptance/dsc_type/custom_resource_path_spec.rb
- spec/acceptance/dsc_type/multiple_dsc_resources_in_PSModulePath_spec.rb
- spec/acceptance/dsc_type/psdesiredstateconfiguration_spec.rb
- spec/acceptance/reboot/negative/reboot_graph_cycle_spec.rb
- spec/acceptance/reboot/reboot_autonotify_explicit_spec.rb
- spec/acceptance/reboot/reboot_no_invoke_warning_spec.rb
- spec/acceptance/unicode/puppet_apply_utf8_file_name_spec.rb
- spec/lib/dsc_utils.rb
Modified the currently non-running reboot tests to reflect dsc_ prefix name change
Modified dsc_util to look for the same module path in both agnet and master/agent runs
Added "--detailed-exitcodes" to make puppet calls look like "puppet(apply --detailed-exitcodes)" so that we can detect the correct exit codes.
> (MODULES-6517) add --detailed-exitcodes 

- lib/puppet/type/dsc.rb
- spec/acceptance/basic_dsc_resources/failing_dsc_resources_spec.rb
- spec/acceptance/basic_functionality/puppet_apply_dsc_manifest_spec.rb
This commit changes the message that Puppet returns when dsc_lite
resources are run from "created" to "invoked". This is because at the
moment, when we invoke a dsc_lite resource, Puppet does not know if the
resource we want to manage has actually been created, or if in reality
it has simply been modified, or even deleted. Changing to invoked is
more ambiguous, but accurately reflects the idea that we don't truly
know what operation dsc has accomplished for us.
> (MODULES-7179) Change created to invoked

- README.md
Previously the trade offs link was relative to the README, however, on the Forge this does not work.  This commit updates the link to be absolute.
> (MODULES-7437) Use absolute link in README

- lib/puppet/provider/base_dsc_lite/powershell.rb
- lib/puppet/type/dsc.rb
- spec/unit/puppet/type/dsc_spec.rb
- Prior to this commit, all types would report the `dsc` type as their
identity. This is problematic for the sake of reporting as every type
of resource is grouped together under `dsc`, rather than the specific
`resource_name` modeled in a manifest.
This new approach allows for types to report under something more
useful that indicates the original DSC resource type specified in the
resource_name attribute.
For instance, given a manifest with the following resources:
```puppet
dsc { 'sample_file':
resource_name     => 'File',
module            => 'PSDesiredStateConfiguration',
properties        => {
ensure          => 'present',
contents        => 'hello',
destinationpath => 'c:\\test.txt',
}
}
dsc { 'lmhosts':
resource_name     => 'Service',
module            => …
```
> (MODULES-7178) Report types dynamically

- lib/puppet/type/dsc.rb
- spec/unit/puppet/type/dsc_spec.rb
This commit uses global type validation to require the `module`,
`resources_name`, and `properties`, instead of `isrequired`. `isrequired`
does not work ( see https://projects.puppetlabs.com/issues/4049 / https://tickets.puppetlabs.com/browse/PUP-1591 )
> (MODULES-7485) Fix validation for required parameters

- lib/puppet/feature/dsc_lite.rb
- 914d934651a68efd2f107f2ed5e36f5449929b5a introduced a new feature for
dsc_lite. In situations where the proper WMF5 version was not
available, a warning would be generated using the Puppet.warn_once
helper.
However, it was not realized that Puppet 4 and Puppet 5 have
different numbers of arguments that can be passed to warn_once, and
that only Puppet 5 supported changing warning to error.
That change was introduced in
https://github.com/puppetlabs/puppet/commit/3d823370884f032368d118e045af86bf54386a63
- Calling a Ruby method with too many arguments causes a Ruby crash and
results in a completely terminated Puppet run that produces no report
for the master. In other words, this is a completely catastrophic
failure case.
- Resolve this problem by checking the arity of the Puppet.warn_once …
> (MODULES-7554) Fix crash on Puppet 4 / WMF < 5

- README.md
With native Puppet types (including the `dsc_*` types), we're used to being able use `puppet describe` to explore the types and discover available parameters. When porting from `dsc` to `dsc_lite`, the lack of that ability might be a sticking point, especially for admins who primarily administer Linux boxes and aren't comfortable enough with PowerShell to know how to do this on their own.
To mitigate that, we'll just show an example in the REAME.
(Can someone with an actual Windows box correct this example to be consistent with the `WindowsFeature` code snippets that follow?)
> Add an example of identifying available parameters

- README.md
The previous code example used a shorthand PowerShell syntax that is not
best practice to put into documentation. It also used a PowerShell DSC
resource that is not installed by default on Windows machines.
> (MAINT) Improve Readme Code Example

- lib/puppet/provider/base_dsc_lite/invoke_dsc_resource.ps1.erb
- lib/puppet/provider/base_dsc_lite/invoke_generic_dsc_resource.ps1.erb
Prior to this commit the helper function `new-pscredential`
in the template used to invoke DSC resources attempted to
cast an incoming value for password to a string. When passed
a hashtable, it was unable to extract the password for use
and instead set the password as the typename for the object.
This happened when the catalog was compiled on a Puppet 5
master to apply to a Puppet 6 agent or when compiled on a
Puppet 6 master for a Puppet 5 agent and specifying the
password using the sensitive datatype.
This problem was introduced in MODULES-8597 when the tags
for rich data serialization were changed from `__pcore_type_`
and `__pcore_value__` to the shorter `__ptype` and `__pvalue`.
After this change, the master and agent both expect different
keys for the sensitive data type, which is …
> (MODULES-8175) Add safety to new-pscredential helper

- lib/puppet/type/dsc.rb
- lib/puppet_x/puppetlabs/dsc_lite/dsc_type_helpers.rb
- spec/unit/puppet/type/dsc_spec.rb
Prior to this commit the PowerShell template code included a workaround
which munged a malformed hash (which should have been a sensitive value)
in the `New-PSCredential` method.
This commit adds a deserialization method and uses it in the munging
of the properties hash itself, obviating the need to handle this in
the PowerShell template code.
This also handles sensitive values for things other than the
MSFT_Credential DSC type, which the prior implementation did not.
> (MODULES-8175) Munge Properties Hash for Sensitive

- README.md
A customer reported to us that the snippet in the readme for handling
reboots was not correct, and would result in un wanted reboots on
nodes. This change ensures that only reboots requested by this module
are executed.
> (MODULES-7716) Fix Readme Reboot Snippet

- spec/integration/puppet_x/puppetlabs/powershell_manager_spec.rb
- spec/integration/puppet_x/puppetlabs/powershell_version_spec.rb
- spec/unit/puppet_x/puppetlabs/powershell_version_spec.rb
to facilitate more complete test output from our unit tests.
> (WIN-280) add skip() unless pattern to tests

- CHANGELOG.md
- lib/puppet/provider/base_dsc_lite/powershell.rb
- lib/puppet_x/puppetlabs/dsc_lite/powershell_hash_formatter.rb
- spec/integration/puppet_x/puppetlabs/powershell_hash_formatter_spec.rb
- spec/unit/puppet/provider/powershell_spec.rb
Prior to this commit the provider would output the full Powershell log to be executed during debug runs. This is to ensure that we can verify exactly what will be executed. However, this also meant that credentials and other secrets could leak into the debug output, and thus also into PuppetDB logs.
This commit modifies the provider, ERB templates, and a helper file to ensure that methods for formatting Puppet data to be PowerShell compliant are able to take a new parameter, `redact`.
Passing this parameter will cause the script builder to redact any sensitive data it is passed. This flag is forwarded along through several helpers. This implementation allows us to reuse the code for interpolating the correct values into the PowerShell script for the actual execution and for the debug …
> (MODULES-8856) Redact debug

- CHANGELOG.md
- lib/puppet_x/puppetlabs/dsc_lite/powershell_manager.rb
This commit increases the timeout for waiting on the named
pipe to open. This resolves isssues where servers under
heavy load do not open the pipe quickly enough.
NOTE: The code for the PowerShell Code Manager in this
module is out of date with fixes distributed to other
modules and should be updated in a separate ticket.
> (MODULES-9086) Increase pipe timeout to 180

- lib/puppet/provider/base_dsc_lite/powershell.rb
I have changed the name of the variable 'COMMAND_TIMEOUT' to 'DSC_LITE_COMMAND_TIMEOUT'. The reason for this change is that this resolves a double declaration issue when using both DSC and DSC_Lite modules on the same Puppet master.
> (MODULES-8602) Resolved declaration conflict between DSC/DSC_Lite

- lib/puppet_x/puppetlabs/dsc_lite/powershell_manager.rb
Prior to this commit, Puppet fails while compiling C# code within init_ps.ps1 with a cryptic no implicit conversion of nil into String message.
This commit checks that the LIB environment variable contains invalid paths and fails with a useful error message.
> (MODULES-8171) Run fails if paths in $env:lib don't exist

- CHANGELOG.md
- README.md
Add a note in the readme that specifies the exact PowerShell version
required to make the module function. While 99% of customers will get
the correct version if they install WMF 5, there was a version released
that will not satisfy this requirement.
> (MODULES-7762) State Exact PS Version Requirement

- lib/puppet_x/puppetlabs/dsc_lite/powershell_version.rb
Prior to this commit the library code for retrieving the powershell
version on the box had a failing guard which gated the requiring of
win32/registry behind a platform-dependent check, but not the rest
of the logic which relies on that code.
This commit corrects the regression.
> (MAINT) Fix powershell_version OS guard

- lib/puppet_x/puppetlabs/dsc_lite/powershell_manager.rb
- spec/integration/puppet_x/puppetlabs/powershell_manager_spec.rb
Prior to this commit, the function that checks for valid paths in the
`lib` environment variable was broken. It would return true, and raise
an error if any value at all was assigned to that variable.
This commit fixes the behavior of that function and unit tests it to
prevent regressions.
> (MODULES-9800) Fix Lib Environment Variable Check

- .sync.yml
- Gemfile
- HISTORY.md
- metadata.json
This adds support for the Github Changelog generator gem by:
- Adding gem to Gemfile
- Adding Rake tasks to Rakefile
- Fixing up the `2.0.2` tag in the HISTORY.md tags to allow parsing by the Changelog Generator gem
> NOTE: Normally the Gemfile and Rakefile changes would have been done by running `pdk update` after adding the necessary changes to `.sync.yml`, but in this case I have just manually added the changes as RSpec deprecated method issues were being introduced after the `pdk update`. This was going to be a bigger task to resolve and will be addressed in [MODULES-9515](https://tickets.puppetlabs.com/browse/MODULES-5915)
> Add Github Changelog Generator gem

- lib/puppet/type/dsc.rb
- spec/unit/puppet/type/dsc_spec.rb
Prior to this PR, the namevar in the dsc type allowed a subset of
characters. This was not a functional limit and did not need to be in
place. This PR removes this restriction and ensure the name is a
string.
This PR also fixes the spec tests for the `resource_name` as
they were only testing the `name` parameter. This just updates it to test the `resource_name` and removes the spec tests for the special character limitations.
> (MODULES-10471) Allow namevar to have special chars

- Gemfile
Due to https://github.com/octokit/octokit.rb/issues/1392, the changelog
generator cannot authenticate properly, which means that it rate limits
almost instantly and takes many hours to generate a changelog. This
should be reverted when that issue is resolved.
> (maint) This is a stop-gap for a breaking octokit change

- CODEOWNERS
DevX team is taking ownership of the codebase. This change is to reflect that in the CODEOWNERS file.
> (CAT-1774) Change ownership to DevX

- lib/puppet/provider/base_dsc_lite/powershell.rb
This fixes these 2 deprecation warnings which appear on each puppet-run:
```
Info: Applying configuration version '1711367415'
C:/ProgramData/PuppetLabs/puppet/var/lib/puppet/provider/base_dsc_lite/powershell.rb:153: warning: Passing safe_level with the 2nd argument of ERB.new is deprecated. Do not use it, and specify other arguments as keyword arguments.
C:/ProgramData/PuppetLabs/puppet/var/lib/puppet/provider/base_dsc_lite/powershell.rb:153: warning: Passing trim_mode with the 3rd argument of ERB.new is deprecated. Use keyword argument like ERB.new(str, trim_mode: ...) instead.
```
Could you please merge it and publish a new version on the forge?
> Fix ERB.new depracation notices

- metadata.json
Remove Windows 7, 8.x and 2008 R2 Support, these platforms are no longer supported by puppet agent and therefore cannot be supported for use with this module.
> (CAT-1927) - Remove Windows 7, 8.x and 2008 R2 Support

- README.md
This PR adds a warning the readme about the use of sensitive data with script block logging enabled. As per microsoft's own recommendation, protected event logging should also be enabled to encyrpt this data.
> (maint) - add disclaimer for script block logging

- lib/puppet/provider/base_dsc_lite/powershell.rb
- spec/acceptance/dsc_type/psdesiredstateconfiguration_spec.rb
Ths commit fixes the timeout matcher to more accurately match a legitimate dsc timeout. Before, if output was nil for any other reason dsc_lite would assume timeout which is not strictly correct. There is a specific error message returned on dsc timeout which we should strive to match instead.
Additionally, moved the logic to only execute for nodes with windows powershell support as we can only pass a timeout to powershell on these nodes, and use the default error output from powershell as it is more concise and does a better job of conveying the message.
> (Bug) - Fix timeout matcher

- lib/puppet/provider/base_dsc_lite/powershell.rb
- lib/puppet/type/dsc.rb
- spec/fixtures/dsc_puppetfakeresource/dsc_puppetfakeresource.rb
A recent investigation revealed the presence of untreated legacy facts in the module. This commit addresses the issue by updating them to their modern counterparts.
> (MAINT) Addressing undetected legacy facts

- .gitignore
- .pdkignore
- .puppet-lint.rc
- .rubocop.yml
- Gemfile
- Rakefile
- metadata.json
- spec/spec_helper.rb
- spec/spec_helper_acceptance.rb
Puppet 7 is EOL. Therefore, we can remove the test infrastructure for it. This PR aims to clear up any testing/config infrastructure related to Puppet 7 and, by extension, Ruby 2.7.
> (CAT-2281) Remove puppet 7 infrastructure
